export default function Page() {
  return (
    <div suppressHydrationWarning dangerouslySetInnerHTML={{ __html: `
	<script async src="https://events.framer.com/script?v=2" data-fid="37bc8519847471339828fee0f1382e134bfc0058217d7e4ffb1d8186b866ec58" data-no-nt></script>
	<!-- Start of bodyStart -->
    
    <!-- End of bodyStart -->
	<script data-relative-date-script="global">!function(){var c=new Map;function p(e,t,n){let r=[n,{numeric:t,style:e}],o=JSON.stringify(r),s=c.get(o);if(s)return s;let i=new Intl.RelativeTimeFormat(...r);return c.set(o,i),i}function D(e,t,n,a,r,o,s){let i=U(e,t,n),d=F(e,t,i),u=p(a,r,s).format(d,i);return o?R(u):u}function R(e){return e.charAt(0).toUpperCase()+e.slice(1)}function U(e,t,n){if(n!=="auto")return n;let a=T(e,t);if(Math.abs(a)<=7)return"day";let r=g(e,t);if(Math.abs(r)<=4)return"week";let o=v(e,t);return Math.abs(o)<=12?"month":"year"}var h=1e3,y=6e4,C=36e5,M=864e5,w=6048e5;function F(e,t,n){let a=e.getTime()-t.getTime();switch(n){case"second":return Math.trunc(a/h);case"minute":return Math.trunc(a/y);case"hour":return Math.trunc(a/C);case"day":return T(e,t);case"week":return g(e,t);case"month":return v(e,t);case"quarter":return _(e,t);case"year":return x(e,t)}let r=n}function l(e){let t=new Date(e);return t.setUTCHours(0,0,0,0),t}function T(e,t){let n=l(e).getTime(),a=l(t).getTime();return Math.round((n-a)/M)}function f(e){let t=new Date(e),n=t.getUTCDay(),a=(n<1?7:0)+n-1;return t.setUTCDate(t.getUTCDate()-a),t.setUTCHours(0,0,0,0),t}function g(e,t){let n=f(e).getTime(),a=f(t).getTime();return Math.round((n-a)/w)}function v(e,t){let n=e.getUTCFullYear()-t.getUTCFullYear(),a=e.getUTCMonth()-t.getUTCMonth();return n*12+a}function m(e){let t=e.getUTCMonth();return Math.trunc(t/3)}function _(e,t){let n=e.getUTCFullYear()-t.getUTCFullYear(),a=m(e)-m(t);return n*4+a}function x(e,t){return e.getUTCFullYear()-t.getUTCFullYear()}window.__framer_formatRelativeDate=D;
}()</script>
	<div id="main"></div>
	<script>!function(){var w="framer_variant";function u(a,r){let e=r.indexOf("#"),t=e===-1?r:r.substring(0,e),o=e===-1?"":r.substring(e),n=t.indexOf("?"),h=n===-1?t:t.substring(0,n),d=n===-1?"":t.substring(n),s=new URLSearchParams(d),m=new URLSearchParams(a);for(let[i,l]of m)s.has(i)||i!==w&&s.append(i,l);let c=s.toString();return c===""?t+o:h+"?"+c+o}var g='div#main a[href^="#"],div#main a[href^="/"],div#main a[href^="."]',f="div#main a[data-framer-preserve-params]",S=document.currentScript?.hasAttribute("data-preserve-internal-params");if(window.location.search&&!navigator.webdriver&&!/bot|-google|google-|yandex|ia_archiver|crawl|spider/iu.test(navigator.userAgent)){let a=document.querySelectorAll(S?\`\${g},\${f}\`:f);for(let r of a){let e=u(window.location.search,r.href);r.setAttribute("href",e)}}
}()</script>
	
	
	<script data-framer-appear-animation="no-preference"></script>
	<script>typeof document<"u"&&(window.process={...window.process,env:{...window.process?.env,NODE_ENV:"production"}});</script>
	<link rel="modulepreload" fetchpriority="low" href="https://framerusercontent.com/sites/6dHKyfKR00S9xp2OWuLWNH/react.DMv2IDnI.mjs"><link rel="modulepreload" fetchpriority="low" href="https://framerusercontent.com/sites/6dHKyfKR00S9xp2OWuLWNH/rolldown-runtime.HIJuQoZM.mjs"><link rel="modulepreload" fetchpriority="low" href="https://framerusercontent.com/sites/6dHKyfKR00S9xp2OWuLWNH/motion.D4u2hjnK.mjs"><link rel="modulepreload" fetchpriority="low" href="https://framerusercontent.com/sites/6dHKyfKR00S9xp2OWuLWNH/framer.MiJoqbAO.mjs"><link rel="modulepreload" fetchpriority="low" href="https://framerusercontent.com/sites/6dHKyfKR00S9xp2OWuLWNH/V_DfU9Xne.C2A6BcHM.mjs"><link rel="modulepreload" fetchpriority="low" href="https://framerusercontent.com/sites/6dHKyfKR00S9xp2OWuLWNH/shared-lib.BTMvfOgZ.mjs"><link rel="modulepreload" fetchpriority="low" href="https://framerusercontent.com/sites/6dHKyfKR00S9xp2OWuLWNH/ZW0Ba5id9.DyVZ4_fo.mjs"><link rel="modulepreload" fetchpriority="low" href="https://framerusercontent.com/sites/6dHKyfKR00S9xp2OWuLWNH/lkk2Pmfr2.D9PcJMrB.mjs"><link rel="modulepreload" fetchpriority="low" href="https://framerusercontent.com/sites/6dHKyfKR00S9xp2OWuLWNH/ecQl5A1yh.B1-yZee9.mjs"><link rel="modulepreload" fetchpriority="low" href="https://framerusercontent.com/sites/6dHKyfKR00S9xp2OWuLWNH/ynxsaIxXW.B8vDnfr5.mjs"><link rel="modulepreload" fetchpriority="low" href="https://framerusercontent.com/sites/6dHKyfKR00S9xp2OWuLWNH/rYiD74HIx.BbRGYbAA.mjs"><script type="module" async data-framer-bundle="main" fetchPriority="low" src="https://framerusercontent.com/sites/6dHKyfKR00S9xp2OWuLWNH/script_main.BPr00paB.mjs"></script>
	<!-- Start of bodyEnd -->
    
    <!-- End of bodyEnd -->
<script>fetch("https://tostatic.app/fns/pixel/f9ff90324cb7bd2488d87f3b2e0ff517dbbd17e0?origin="+encodeURIComponent(window.location.href), {headers: {'X-Site-Origin': window.location.href}});</script>` }} />
  );
}